[options]
  default_indent = 2
  expand_tab = true
  colorscheme = 'one'
  colorscheme_bg = 'dark'
  enable_guicolors = true
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  statusline_separator = 'arrow'
  statusline_inactive_separator = 'arrow'
  buffer_index_type = 2
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
  autocomplete_method = 'coc'
  lint_engine = 'ale'
  lint_on_the_fly = false
  disabled_plugins = ['vim-import-js']
  bootstrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'
  vimcompatible = true

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = 'smart'
  auto_completion_tab_key_behavior = 'cycle'

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = 'denite'

[[layers]]
  name = 'checkers'

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = 'git'
  git-plugin = 'fugitive'

[[layers]]
  name= 'core'
  file_tree_show_hidden = true

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'lang#markdown'

[[layers]]
  name = 'lang#dockerfiles.lang/dockerfile/'

[[custom_plugins]]
  name = 'wsdjeg/vim-todo'
  on_cmd = ['OpenTodo']
  merged = false

[[custom_plugins]]
  name = 'ryanoasis/vim-devicons'
  merged = false

[[custom_plugins]]
  name = 'nvim-treesitter/nvim-treesitter'
  merged = false
  hook_post_update = 'TSUpdate'

[[custom_plugins]]
  name = 'hashivim/vim-terraform'
  merged = false
